# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_AY0HtKd2_TNQXjYPA_s17bTWvxyo-gb
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression

# %matplotlib inline

raw_df = pd.read_csv('https://grantmlong.com/data/SE_rents2018_train.csv', index_col=0)
raw_df.head(20)
raw_df.columns

"""# Data Summarize"""

raw_df.describe()

raw_df.shape

raw_df.info()

raw_df['rent'].hist(bins=100)

"""### Seperate all features into continuses, caterigal and binary features."""

continues_features =['bathrooms','bedrooms','size_sqft','floor_count','year_built','min_to_subway','floornumber' ]
caterigal_features =['addr_street','addr_city','addr_zip','neighborhood','borough','line' ]
binary_features = ['has_doorman', 'has_elevator', 'has_fireplace', 'has_dishwasher','is_furnished', 'has_gym', 'allows_pets', 
                   'has_washer_dryer','has_garage', 'has_roofdeck', 'has_concierge', 'has_pool', 'has_garden',
                   'has_childrens_playroom', 'no_fee', ]
# use to check how many unique number for each features
unique_count = [] 
for feature in raw_df.columns:
  unique_count.append(raw_df[feature].nunique())
count_df = pd.DataFrame({'Feature':raw_df.columns,'unique count': unique_count})
count_df

"""# use pair coorelation for continues features"""

continuous_df = raw_df[continues_features+['rent']]
continuous_df.corr()['rent'][:-1]

"""### Create a scatterplot of continuous features."""

sns.pairplot(data = raw_df,  y_vars=['rent'],x_vars=['bathrooms','bedrooms','size_sqft','floor_count','floornumber','neighborhood','borough','line'])

"""### Check coorelation for binary features"""

raw_df[binary_features+['rent']].corr()['rent'][:-1]
coor_results= []
for feature in binary_features:
  df = raw_df.groupby([feature]).aggregate(['mean'])['rent']
  df[feature]= df.index
  coor_results.append(df.corr().iloc[0][1])
coor_df = pd.DataFrame({'Coorelation': coor_results,'Feature':binary_features})
coor_df



"""### Check coorelation for caterigal features"""





